### ISSUE TITLE
hi, why did you remove me from friends in discord?

### ISSUE THREAD

**Issue by kisman2000** [synnkfps/JByteCustom#11]
hi, why did you remove me from friends in discord?

**Comment by storm772** [comment]
i got token logged

**Comment by kisman2000** [comment]
hi, that's what I understood, can you please make a new discord and write to me if that's my new discord: _kisman_#5039

**Comment by kisman2000** [comment]
I'm sorry I didn't answer, for some reason my page wasn't updated, and now I went to the mail and saw that you answered me

**Comment by kisman2000** [comment]
you last discord account is deleted?
